# Generated by Django 6.0.4 on 2026-04-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacademico',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_academicos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='eventociberseguranca',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ciberseguranca', to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
